[programs.localnet]
transmuter = "muto7o7vvfXcvpy5Qgjtaog7GRhtr9Zpzn7PSCmmF8Z"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "./tests/test-key.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[[test.genesis]]
address = "bankHHdqMuaaST4qQk6mkzxGeKPHWmqdgor6Gs8r88m"
program = "./tests/programs/gem_bank.so"