[programs.localnet]
transmuter = "4c5WjWPmecCLHMSo8bQESo26VCotSKtjiUpCPnfEPL2p"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "./tests/test-key.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[[test.genesis]]
address = "bankHHdqMuaaST4qQk6mkzxGeKPHWmqdgor6Gs8r88m"
program = "./tests/programs/gem_bank.so"